PROFILES = {
    "quick": {
        "cpu_rounds": 3,
        "cpu_units": 32,
        "cpu_span": 640,
        "cpu_workers_cap": 8,
        "dev_rounds": 3,
        "dev_iterations": 1500,
        "memory_fraction": 0.05,
        "memory_cap_mb": 192,
        "memory_chunk_mb": 8,
        "memory_floor_mb": 256,
        "system_rounds": 2,
        "system_files": 24,
        "system_payload_kb": 32,
        "gpu_rounds": 2,
        "gpu_size": 96,
        "gpu_iters": 3,
    },
    "standard": {
        "cpu_rounds": 4,
        "cpu_units": 48,
        "cpu_span": 800,
        "cpu_workers_cap": 12,
        "dev_rounds": 4,
        "dev_iterations": 3000,
        "memory_fraction": 0.08,
        "memory_cap_mb": 512,
        "memory_chunk_mb": 16,
        "memory_floor_mb": 384,
        "system_rounds": 3,
        "system_files": 40,
        "system_payload_kb": 56,
        "gpu_rounds": 3,
        "gpu_size": 128,
        "gpu_iters": 4,
    },
    "stress": {
        "cpu_rounds": 5,
        "cpu_units": 64,
        "cpu_span": 960,
        "cpu_workers_cap": 16,
        "dev_rounds": 5,
        "dev_iterations": 5000,
        "memory_fraction": 0.12,
        "memory_cap_mb": 1024,
        "memory_chunk_mb": 32,
        "memory_floor_mb": 512,
        "system_rounds": 4,
        "system_files": 56,
        "system_payload_kb": 72,
        "gpu_rounds": 4,
        "gpu_size": 160,
        "gpu_iters": 5,
    },
}

SCORE_REFERENCES = {
    "cpu_ops": 1300000,
    "dev_ops": 7500,
    "memory_throughput": 4500,
    "memory_spread": 1.8,
    "system_ops": 110,
    "gpu_gflops_accelerated": 250,
    "gpu_gflops_fallback": 0.3,
}
